
logging:
  level:
    root: INFO

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sublearndb
    username: postgres
    password: passw0rd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

default:
  user:
    setting:
      wordCountInTrial: 20
      answerOptionsCount: 4
      isRemindAboutTrial: false
      thresholdLearnedPercent: 75
      isShowAllTranslate: true

translator:
  url: http://ms-sublearn-translator:8080/api/translator