
logging:
  level:
    root: INFO

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sublearndb
    username: postgres
    password: passw0rd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
        loggerLevel: basic

default:
  user:
    setting:
      wordCountInTrial: 20
      answerOptionsCount: 4
      isRemindAboutTrial: false
      thresholdLearnedPercent: 75
      isShowAllTranslate: true
      learnedWordCount: 3

translator:
  url: http://ms-sublearn-translator:8080/api/translator

project:
  version: @project.version@

sublearn:
  back:
    user:
      login:
      password:
    admin:
      login:
      password: