version: '3.4'

services:
  ms-sublearn-back:
    image: ms-sublearn-back
    depends_on:
      - sublearn-db
    ports:
      - 8080:8080
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://sublearn-db:5432/sublearndb
        SPRING_PROFILES_ACTIVE: default
        SERVER_PORT: 8080

  sublearn-db:
    container_name: sublearn-db
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: sublearndb
    ports:
      - 15432:5432